export const genresList = [
  { id: 1, name: "Action" },
  { id: 2, name: "Adventure" },
  { id: 4, name: "Comedy" },
  { id: 8, name: "Drama" },
  { id: 10, name: "Fantasy" },
  { id: 12, name: "Hentai" },
  { id: 15, name: "Horror" },
  { id: 22, name: "Romance" },
  { id: 24, name: "Sci-Fi" },
  { id: 36, name: "Slice of Life" },
  { id: 37, name: "Supernatural" },
  { id: 40, name: "Psychological" },
  { id: 41, name: "Thriller" },
  { id: 18, name: "Mecha" },
  { id: 30, name: "Sports" },
  { id: 19, name: "Music" },
  { id: 38, name: "Military" },
  { id: 42, name: "Seinen" },
  { id: 27, name: "Shounen" },
  { id: 25, name: "Shoujo" },
];
